export const GET_LOCATIONS_ACTION = 'GET_LOCATIONS_ACTION'
export const GET_LOCATIONS_SUCCESS = 'GET_LOCATIONS_ACTION_SUCCESS'
export const GET_LOCATIONS_ERROR = 'GET_LOCATIONS_ACTION_ERROR'

export const SET_NEW_LOCATION_ACTION = 'SET_NEW_LOCATION_ACTION'
export const SET_SELECTED_LOCATION_ACTION = 'SET_SELECTED_LOCATION_ACTION'

export const CREATE_LOCATION_ACTION = 'CREATE_LOCATION_ACTION'
export const CREATE_LOCATION_SUCCESS = 'CREATE_LOCATION_ACTION_SUCCESS'
export const CREATE_LOCATION_ERROR = 'CREATE_LOCATION_ACTION_ERROR'
