export const GET_MEMBERS_ACTION = 'GET_MEMBERS_ACTION'
export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_ACTION_SUCCESS'
export const GET_MEMBERS_ERROR = 'GET_MEMBERS_ACTION_ERROR'

export const CREATE_MEMBER_ACTION = 'CREATE_MEMBER_ACTION'
export const CREATE_MEMBER_SUCCESS = 'CREATE_MEMBER_ACTION_SUCCESS'
export const CREATE_MEMBER_ERROR = 'CREATE_MEMBER_ACTION_ERROR'
