export const GET_TEAMS_ACTION = 'GET_TEAMS_ACTION'
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_ACTION_SUCCESS'
export const GET_TEAMS_ERROR = 'GET_TEAMS_ACTION_ERROR'

export const CREATE_TEAM_ACTION = 'CREATE_TEAM_ACTION'
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_ACTION_SUCCESS'
export const CREATE_TEAM_ERROR = 'CREATE_TEAM_ACTION_ERROR'

export const DELETE_TEAM_ACTION = 'DELETE_TEAM_ACTION'
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_ACTION_SUCCESS'
export const DELETE_TEAM_ERROR = 'DELETE_TEAM_ACTION_ERROR'

export const EDIT_TEAM_ACTION = 'EDIT_TEAM_ACTION'
export const EDIT_TEAM_SUCCESS = 'EDIT_TEAM_ACTION_SUCCESS'
export const EDIT_TEAM_ERROR = 'EDIT_TEAM_ACTION_ERROR'

export const EDIT_TEAM_MEMBER_SUCCESS =
  'EDIT_TEAM_MEMBER_ACTION_SUCCESS'

export const DELETE_TEAM_MEMBER_SUCCESS = 'DELETE_TEAM_MEMBER_SUCCESS'
