export const GET_TEAMS_ACTION = 'GET_TEAMS_ACTION'
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_ACTION_SUCCESS'
export const GET_TEAMS_ERROR = 'GET_TEAMS_ACTION_ERROR'

export const CREATE_TEAM_ACTION = 'CREATE_TEAM_ACTION'
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_ACTION_SUCCESS'
export const CREATE_TEAM_ERROR = 'CREATE_TEAM_ACTION_ERROR'
